spring:
  profiles:
    active: docker

  flyway:
    locations: ["classpath:db/migration"]
    validate-on-migrate: true
    placeholder-replacement: false

# 阿里云
ali:
  # 短信服务
  sms:
    region: cn-shanghai
    sign-name: Jext技术社区
    access-key: input_your_own_access_key
    secret-key: input_your_own_secret_key

  # api网关
  api:
    app-code: input_your_own_app_code

  # OSS云存储
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKey: input_your_own_access_key
    secretKey: input_your_own_secret_key

# API文档
swagger:
  production: false
  basic:
    enable: false
    username: jeecg
    password: jeecg1314
# 第三方登录
justauth:
  enabled: true
  type:
    GITHUB:
      client-id: 0277e675495f14a4a183
      client-secret: ??
      redirect-uri: http://sso.test.com:8080/jeecg-boot/thirdLogin/github/callback
    WECHAT_ENTERPRISE:
      client-id: wwc2a8c8b19c201bcc
      client-secret: ??
      redirect-uri: http://sso.test.com:8080/jeecg-boot/thirdLogin/wechat_enterprise/callback
      agent-id: 1000002
    DINGTALK:
      client-id: dingoa33vjqxrbyidnmgwo
      client-secret: ？？
      redirect-uri: http://sso.test.com:8080/jeecg-boot/thirdLogin/dingtalk/callback
  cache:
    type: default
    prefix: 'demo::'
    timeout: 1h